apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ridely-database.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ridely-database.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "ridely-database.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: mysql:8
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ridely-database.fullname" . }}-secret
                  key: mysql-root-password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          ports:
            - name: {{ .Chart.Name }}
              containerPort: 3306
              protocol: TCP
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 400Mi
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{ include "ridely-database.fullname" . }}-pvc
{{/*      {{- with .Values.nodeSelector }}*/}}
{{/*      nodeSelector:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      {{- with .Values.affinity }}*/}}
{{/*      affinity:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      {{- with .Values.tolerations }}*/}}
{{/*      tolerations:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}

