apiVersion: v1
kind: Service
metadata:
  name: {{ include "ridely-database.fullname" . }}
{{/*  labels:*/}}
{{/*    {{- include "ridely-database.labels" . | nindent 4 }}*/}}
spec:
{{/*  type: {{ .Values.service.type }}*/}}
  ports:
    - port: 3306
      targetPort: {{ .Chart.Name }}
      protocol: TCP
      name: {{ include "ridely-database.fullname" . }}
  selector:
    app: {{ include "ridely-database.fullname" . }}
{{/*    {{- include "ridely-database.selectorLabels" . | nindent 4 }}*/}}
