apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ridely-service.fullname" . }}-php-fpm
spec:
  replicas: {{ .Values.php.replicas }}
  selector:
    matchLabels:
      app: {{ include "ridely-service.name" . }}-php-fpm
  template:
    metadata:
      labels:
        app: {{ include "ridely-service.name" . }}-php-fpm
    spec:
      # TODO revisar para que o PHP possa ter mais instancias quando necessário
      containers:
        - name: laravel
          image: "{{ .Values.images.php.repository }}:{{ .Values.images.php.tag }}"
          imagePullPolicy: {{ .Values.images.php.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ridely-service.fullname" . }}-secret
                  key: database-password
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ridely-service.fullname" . }}-secret
                  key: app-key
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ridely-service.fullname" . }}-secret
                  key: keycloak-client-secret
          ports:
            - containerPort: 9000
          # TODO migrar para values
          resources:
            requests:
              cpu: {{ .Values.php.resources.requests.cpu }}
              memory: {{ .Values.php.resources.requests.memory }}
            limits:
              cpu: {{ .Values.php.resources.limits.cpu }}
              memory: {{ .Values.php.resources.limits.memory }}
          volumeMounts:
            - name: www-conf
              mountPath: /usr/local/etc/php-fpm.d/www.conf
              subPath: www.conf
      volumes:
        - name: www-conf
          configMap:
            name: {{ include "ridely-service.fullname" . }}-php-fpm-www-conf