apiVersion: v1
kind: Service
metadata:
  name: {{ include "ridely-service.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app: {{ include "ridely-service.fullname" . }}