@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

'-----------------------------------------
'Personas
'-----------------------------------------
Person(user, "Customer", "People that request taxi services")
Person(admin, "Administrator", "People that administrates the system")

'-----------------------------------------
'Sistemas
'-----------------------------------------
System(ridely, "Ridely", "System that provides taxi services")

'-----------------------------------------
'Sistemas externos
'-----------------------------------------

'-----------------------------------------
'Relacionamentos
'-----------------------------------------
Rel(user, ridely, "The user requests a taxi ride")
SHOW_LEGEND()
@enduml