apiVersion: v1
kind: Service
metadata:
  name: {{ include "ridely-database.fullname" . }}
spec:
  selector:
    app: {{ include "ridely-database.fullname" . }}
  ports:
    - port: 3306
      targetPort: {{ .Chart.Name }}
      protocol: TCP
      name: {{ include "ridely-database.fullname" . }}

