@startuml
actor Cliente
participant "RidelyService" as RidelyService
participant "RideController" as Controller
participant "RideService"
participant "Redis Queue" as RedisQueue
participant "ProcessRideEstimates" as ProcessRideEstimates

participant "LocationService"
participant "OpenStreetMap (Nominatim)" as Nominatim
participant "Database"

Cliente -> RidelyService : POST /api/v1/rides/request-driver\n(passenger, pick_up, drop_off)
RidelyService -> Controller : requestDriver()
Controller -> Controller : Append "Aracaju, SE" if needed (EstimateRideCriteria)
Controller -> RideService : create()
RideService -> RideService : create Ride
RideService -> RideService : create Estimate with status "PENDING"

RideService -> RedisQueue : publishToEstimateRideQueue({ride_id, estimate_id, pick_up, drop_off, timestamp})
RideService -> Controller : return (Ride, RideEstimate)
Controller -> RidelyService : return Ride, RideEstimate->status: "processing"
RidelyService --> Cliente : 201 Created

== Async Job ==

ProcessRideEstimates -> RedisQueue : consume message
ProcessRideEstimates -> LocationService : getCoordinates(pick_up)
LocationService -> LocationService : check cache
alt Not in cache
    LocationService -> Nominatim : GET /search?q=pick_up
    Nominatim --> LocationService : lat/lon
    LocationService -> LocationService : store in cache
end

ProcessRideEstimates -> LocationService : getCoordinates(drop_off)
LocationService -> LocationService : check cache
alt Not in cache
    LocationService -> Nominatim : GET /search?q=drop_off
    Nominatim --> LocationService : lat/lon
    LocationService -> LocationService : store in cache
end
ProcessRideEstimates -> ProcessRideEstimates : calculateDistance()
ProcessRideEstimates -> ProcessRideEstimates : calculateDuration()
ProcessRideEstimates -> ProcessRideEstimates : calculatePrice()
ProcessRideEstimates -> Database : save RideEstimate data (result)


@enduml
