[www]
    user = www-data
    group = www-data

    listen = 9000
    ; WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 8 children, there are 0 idle, and 9 total children
    pm = dynamic
    pm.max_children = 48
    pm.start_servers = 8
    pm.min_spare_servers = 4
    pm.max_spare_servers = 16

    catch_workers_output = yes

